### ISSUE TITLE
Where is CC41 main program ?

### ISSUE THREAD

**Issue by mbornet-hl** [CraigBladow/cc41#7]
Hello Craig,
where can CC41 for Linux be found ? I can't see it on your Github repository. I found NQ41 elsewhere but maybe it's not the last version.
Do you plan to open your code and upload it on this Github repository ?

By the way, I have developed an RPN interpreter (inspired by HP calculators) : https://github.com/mbornet-hl/rpn
Maybe you could be interested in seeing what it does.
I also plan to create HP-41 module  for this emulator, but I don't have much free time.

Thank you in advance for you reply.

Kind regards,
Martial

**Comment by CraigBladow** [comment]
Hi Martial,
The executable binaries can be downloaded from the "Releases" section on the right-hand side of the repository main page.  
Download the the v0.42.03.zip file  (or later for releases after the date of this post).  When you extract the files from the zip file you will find the Linux x86 64 bit executable binary in a folder.

Regarding plans for releasing the source please follow the topic in the [Discussion](https://github.com/CraigBladow/cc41/discussions/6) section.

I'll take a look at your project, thank you for your question.

**Comment by mbornet-hl** [comment]
Thank you for your quick reply.
I got the cc41 binary an dsuccessfully ran it on Linux (Devuan).
You can close this issue if you want.
Kind regards,
Martial
